# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17qh0sPcTKctBF5Qui6c_LV1fOySG6NyE
"""

#1

l=int(input("Enter length of the reactagle"))
b=int(input("Enter Breath of the reactagle"))
area=l*b
print("Area of reactangle is",area)

#2

weigth=int(input("Enter Weight of the person"))
height=int(input("Enter heigth of the person"))
bmi=weigth/height**2
print(bmi)

#3
n=int(input("Enter number of students you want"))
d={}
for i in range (0,n):
  x=input("Enter student name")
  y=input("Enter Score")
  d[x]=y

for keys in d.keys():
  print(keys," ", d[keys])

#4
age=int(input("Enter age of person"))
if age<18:
  print("Person is minor")
elif age>=18 and age<=60:
  print("Person is adult")
else:
  print("Person is senior")

# 5

for i in range(50):
  if i%2==0 and i>0:
    print(i)

# 6

users={}
def sign_up():
  user_name=input("Enter Username")
  if user_name in users.keys():
    print("User name already taken")
    return
  password=input("Enter password")
  users[user_name]=password
def login():
  user_name=input("Enter Username")
  password=input("Enter password")
  if password==users[password]:
    print("Login Successfully")
  else:
    print("Wrong Password Please enter the correct password")
    accessControl()
def accessControl():
  user_name=input("Enter Username")
  password=input("Enter new password")
  users[user_name]=password

choice=1
print("What do you want to do")
while choice:
  print("1. For Login\n 2.For Sign Up\n 3. for registration0. Exit")
  choice=int(input("Enter your choice"))
  if choice==1:
    login()
  elif choice==2:
    sign_up()
  elif choice==3:
    accessControl()
  elif choice==0:
    break

# 7
nums = input("enter the list elements").split(",")
size=len(nums)
sum=0
def average(nums):
  for i in range(size):
    sum+=nums[i]
    ans=sum/size
    return ans
average(nums)

#8

def check(str):
 size=len(str)
 for i in range(size):
  if(str[i]=='a' or str[i]=='A' or str[i]=='E' or str[i]=='e' or str[i]=='O' or str[i]=='I' or str[i]=='i' or str[i]=='U' or str[i]=='u')
   count++
  return count
check("Hello")

#9

from datetime import datetime as dt,timedelta

def Timing():
  time=dt.now()
  print(time)


Timing()

# 10

def nonnumeric(num1,num2):
    try:
      return num1+num2
    except TypeError:
      print("Either or both entries are non-numeric")
nonnumeric(1,"abc")

# 11


def value prompt:while true:
  try:
    userinput=input(prompt)
    integervalue=int(userinput) return integervalue
  except valueError:
    print("it is a value error")
value(num)

# 12
def division(num1,num2):
  try:
    return num1/num2
  except ZeroDivisionError:
    print("cannot divide by zero")

division(1,1)

# 13
my_file = open('HelloPython.txt', 'w')
my_file.write("Hello,Python!")
my_file.close()

# 14
def readfromfile(filename):
  withopen(filename,'r') as file:
    content=file.create
return content

filename="hellopython.txt"
file_content=readfromfile(filename)
print(filecontent)

def appendtofile(filename,txt):
  withopen(filename,'a') as file:
    file.write(txt+:\n)
appendtofile('Hello_python.txt',"hello world")
withopen('hellopython,txt' as file)
filecontent=file.read()