# -*- coding: utf-8 -*-
"""LVADSUSR86_Garvit_lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lKiO0kBcAXwKbu3GGbcgFVAp7pRy7ZwA
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('https://raw.githubusercontent.com/Deepsphere-AI/LVA-Batch4-Assessment/main/expenses.csv')

df.head()

missing_value=df.isnull().sum()
print(missing_value)

filling_values=df.fillna(df.mean(), inplace=True)

Dropping_value = df.dropna()
print("Dropping the values:",Dropping_value)
duplicate = df.duplicated().sum()
print("Number of duplicate entries:", duplicate)
Drop_Duplicate = df.drop_duplicates()
print("Dropped off all the duplicate values",Drop_Duplicate)

fig = plt.figure(figsize =(10, 7))
data = df[['age',	'bmi','children','charges']]
sns.boxplot(data)

df.describe()

def cap_data(df):
    for col in df.columns:
        print("capping the ",col)
        if (((df[col].dtype)=='float64') | ((df[col].dtype)=='int64')):
            percentiles = df[col].quantile([0.01,0.99]).values
            df[col][df[col] <= percentiles[0]] = percentiles[0]
            df[col][df[col] >= percentiles[1]] = percentiles[1]
        else:
            df[col]=df[col]
    return df

final_df=cap_data(df)
sns.boxplot(final_df)

final_df['region'].value_counts()

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

final_df['region_encoded'] = label_encoder.fit_transform(final_df['region'])

print(final_df[['region', 'region_encoded']])

final_df['sex_encoded'] = label_encoder.fit_transform(final_df['sex'])

print(final_df[['sex', 'sex_encoded']])

final_df['smoker_encoded'] = label_encoder.fit_transform(final_df['smoker'])

print(final_df[['smoker', 'smoker_encoded']])

final_df.corr()

sns.pairplot(final_df)

df.describe()

final_df.drop(columns = ['childern'],axis=1,inplace=True)

X = final_df[['age',	'bmi'	,'region_encoded'	,'sex_encoded'	,'smoker_encoded']]
y=final_df['charges']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25, random_state=10)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

from sklearn.linear_model import LinearRegression
regression = LinearRegression()

regression.fit(X_train,y_train)

y_pred = regression.predict(X_test)
y_pred

from sklearn.metrics import mean_absolute_error,mean_squared_error

mse = mean_squared_error(y_test,y_pred)
mae = mean_absolute_error(y_test,y_pred)
rmse = np.sqrt(mse)
print(mse)
print(mae)
print(rmse)

from sklearn.metrics import r2_score

score = r2_score(y_test,y_pred)
print(score)

plt.scatter(y_test,y_pred)